kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-user
  namespace: user-1
subjects:
- kind: User
  name: cicd-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: org:cicd-user
  apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-user
  namespace: user-2
subjects:
- kind: User
  name: cicd-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: org:cicd-user
  apiGroup: rbac.authorization.k8s.io
