kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: org:user-2
  namespace: user-2
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - configmaps
  - ingresses
  - secrets
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - get
  - list
  - patch
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - get
  - list
  - patch
  - update
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  - ingresses
  verbs:
  - create
  - get
  - list
  - patch
  - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-2
  namespace: user-2
subjects:
- kind: User
  name: user-2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: org:user-2
  apiGroup: rbac.authorization.k8s.io
