apiVersion: v1
kind: LimitRange
metadata:
  name: set-defaults-limits-requests
  namespace: production-v1
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 200m
    defaultRequest:
      memory: 256Mi
      cpu: 100m
    type: Container

---

apiVersion: v1
kind: LimitRange
metadata:
  name: set-defaults-limits-requests
  namespace: production-v2
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 200m
    defaultRequest:
      memory: 256Mi
      cpu: 100m
    type: Container
